from datetime import date, timedelta
from html import escape
from pathlib import Path
from playwright.async_api import async_playwright

from .database import get_connection

BASE_DIR = Path(__file__).resolve().parent.parent
REPORTS_DIR = BASE_DIR / "reports"


def get_report_data() -> dict:
    with get_connection() as conn:
        total_orders = conn.execute("SELECT COUNT(*) FROM orders").fetchone()[0]
        total_revenue = conn.execute("SELECT COALESCE(SUM(amount), 0) FROM orders").fetchone()[0]
        top_products = conn.execute(
            """SELECT product, COUNT(*) AS order_count, ROUND(SUM(amount), 2) AS revenue
               FROM orders GROUP BY product ORDER BY revenue DESC LIMIT 5"""
        ).fetchall()
        start = date.today() - timedelta(days=6)
        orders_per_day = conn.execute(
            """SELECT substr(created_at, 1, 10) AS day, COUNT(*) AS orders, ROUND(SUM(amount), 2) AS revenue
               FROM orders WHERE date(created_at) >= ? GROUP BY day ORDER BY day""",
            (start.isoformat(),),
        ).fetchall()
        all_orders = conn.execute(
            "SELECT id, customer, product, amount, created_at FROM orders ORDER BY datetime(created_at) DESC, id DESC"
        ).fetchall()
    return {
        "total_orders": total_orders,
        "total_revenue": round(total_revenue, 2),
        "top_products": [dict(row) for row in top_products],
        "orders_per_day": [dict(row) for row in orders_per_day],
        "all_orders": [dict(row) for row in all_orders],
    }


def build_html(data: dict) -> str:
    top_rows = "".join(
        f"<tr><td>{escape(row['product'])}</td><td>{row['order_count']}</td><td>₹{row['revenue']:,.2f}</td></tr>"
        for row in data["top_products"]
    )
    daily_rows = "".join(
        f"<tr><td>{row['day']}</td><td>{row['orders']}</td><td>₹{row['revenue']:,.2f}</td></tr>"
        for row in data["orders_per_day"]
    )
    order_rows = "".join(
        f"<tr><td>{row['id']}</td><td>{escape(row['customer'])}</td><td>{escape(row['product'])}</td>"
        f"<td>₹{row['amount']:,.2f}</td><td>{row['created_at'].replace('T', ' ')}</td></tr>"
        for row in data["all_orders"]
    )
    return f"""<!doctype html>
<html><head><meta charset='utf-8'><style>
@page {{ size: A4; margin: 18mm 14mm; }}
body {{ font-family: Arial, sans-serif; color: #14202b; font-size: 10px; margin: 0; }}
h1 {{ font-size: 24px; margin: 0 0 4px; }} h2 {{ font-size: 14px; margin: 22px 0 8px; }}
.muted {{ color: #667085; }} .cards {{ display: flex; gap: 10px; margin: 16px 0; }}
.card {{ flex: 1; border: 1px solid #d7dee7; border-radius: 8px; padding: 12px; }}
.value {{ font-size: 20px; font-weight: 700; margin-top: 4px; }}
table {{ width: 100%; border-collapse: collapse; margin-top: 6px; }}
th {{ background: #173b4a; color: white; text-align: left; }}
th, td {{ border: 1px solid #d7dee7; padding: 6px; }}
tbody tr:nth-child(even) {{ background: #f6f8fa; }} tr {{ break-inside: avoid; }} thead {{ display: table-header-group; }}
.footer {{ margin-top: 16px; color: #667085; font-size: 9px; }}
</style></head><body>
<h1>Shop Sales Report</h1><div class='muted'>Generated on {date.today().isoformat()}</div>
<div class='cards'><div class='card'><div class='muted'>Total orders</div><div class='value'>{data['total_orders']}</div></div>
<div class='card'><div class='muted'>Total revenue</div><div class='value'>₹{data['total_revenue']:,.2f}</div></div></div>
<h2>Top 5 products by revenue</h2><table><thead><tr><th>Product</th><th>Orders</th><th>Revenue</th></tr></thead><tbody>{top_rows}</tbody></table>
<h2>Orders per day — last 7 days</h2><table><thead><tr><th>Date</th><th>Orders</th><th>Revenue</th></tr></thead><tbody>{daily_rows}</tbody></table>
<h2>All orders</h2><table><thead><tr><th>ID</th><th>Customer</th><th>Product</th><th>Amount</th><th>Created at</th></tr></thead><tbody>{order_rows}</tbody></table>
<div class='footer'>Generated by the FlyRank A8 PDF Report Generator.</div>
</body></html>"""


async def render_pdf(output_path: Path, data: dict | None = None) -> None:
    REPORTS_DIR.mkdir(exist_ok=True)
    data = data or get_report_data()
    html = build_html(data)
    executable_path = "/usr/bin/chromium" if Path("/usr/bin/chromium").exists() else None
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, executable_path=executable_path)
        page = await browser.new_page()
        await page.set_content(html, wait_until="networkidle")
        await page.pdf(path=str(output_path), format="A4", print_background=True)
        await browser.close()
